name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - run: |
        # curl -o mingw.7z "https://ci-mirrors.rust-lang.org/rustc/i686-12.2.0-release-posix-dwarf-rt_v10-rev0.7z"
        7z x -y i686-12.2.0-release-posix-dwarf-msvcrt-rt_v10.0.0-rev0.7z > /dev/null
        export PATH=`pwd`/mingw32/bin:$PATH
        set -m
        which ar
        ar --version
        ranlib --version
        for n in {1..15000}; do rm -f lib/libLLVMAVRAsmParser.a && ar qc lib/libLLVMAVRAsmParser.a lib/Target/AVR/AsmParser/CMakeFiles/LLVMAVRAsmParser.dir/AVRAsmParser.cpp.obj && ranlib.exe lib/libLLVMAVRAsmParser.a; done &
        for n in {1..15000}; do rm -f lib/libLLVMSparcCodeGen.a && ar qc lib/libLLVMSparcCodeGen.a lib/Target/Sparc/CMakeFiles/LLVMSparcCodeGen.dir/*.obj && ranlib.exe lib/libLLVMSparcCodeGen.a; done
        echo "done"
        fg
      shell: bash

  # test1:
  #   name: Test1
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Test1
  #     shell: bash
  #     run: |
  #       cd foo
  #       cargo -V
  #       cargo run
